@php
    // S211 — preload the dominant latin WOFF2 slices generated by BaseHelper::googleFonts().
    $__grimbaFontPreloads = [
        'storage/fonts/2e66a49ab9/sfrauncesv386nu78fylnqoqzanv9byevdiide9ea92uemak-wbq8u-9v0c2wa0kxc9tep2xz5c.woff2',
        'storage/fonts/2e66a49ab9/spublicsansv21ijwrs572xtc6zyqws9yvwnngfj7qwok1.woff2',
    ];
@endphp

@foreach($__grimbaFontPreloads as $__grimbaFontPreload)
    @if(file_exists(public_path($__grimbaFontPreload)))
        <link rel="preload" href="{{ asset($__grimbaFontPreload) }}" as="font" type="font/woff2" crossorigin>
    @endif
@endforeach
