<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Article Hero Image Proxy
    |--------------------------------------------------------------------------
    |
    | Public cards should not ask the reader's browser to hot-link publisher
    | CDNs directly. Keep this list explicit so /img-proxy cannot become a
    | general-purpose SSRF endpoint.
    |
    */

    'article_hero_hosts' => [
        'a57.foxnews.com',
        'assets.bwbx.io',
        'assets3.cbsnewsstatic.com',
        'cdn-s-www.ledauphine.com',
        'cdn.allafrica.com',
        'cdn.lesnumeriques.com',
        'cdn.mos.cms.futurecdn.net',
        'cdn8.futura-sciences.com',
        'cff2.earth.com',
        'dailygalaxy.com',
        'dims.apnews.com',
        'focus.courrierinternational.com',
        'focus.huffingtonpost.fr',
        'focus.nouvelobs.com',
        'fortune.com',
        'france3-regions.franceinfo.fr',
        'gizmodo.com',
        'globalnews.ca',
        'hips.hearstapps.com',
        'i.dailymail.com',
        'i.f1g.fr',
        'i.guim.co.uk',
        'i0.wp.com',
        'ichef.bbci.co.uk',
        'image.cnbcfm.com',
        'images.axios.com',
        'images.bfmtv.com',
        'images.ft.com',
        'images.pushsquare.com',
        'images.theconversation.com',
        'images2.minutemediacdn.com',
        'img.20mn.fr',
        'img.huffingtonpost.com',
        'img.lemde.fr',
        'indiandefencereview.com',
        'media-cldnry.s-nbcnews.com',
        'media.breitbart.com',
        'media.cnn.com',
        'nbcsports.brightspotcdn.com',
        'neurosciencenews.com',
        'npr.brightspotcdn.com',
        'nypost.com',
        'people.com',
        'platform.theverge.com',
        'prod.cdn-medias.jeuneafrique.com',
        's.france24.com',
        's.hdnux.com',
        's.rfi.fr',
        's.w.org',
        'scitechdaily.com',
        'scx2.b-cdn.net',
        'static-mali24.cdn.so',
        'static.foxnews.com',
        'static.mediapart.fr',
        'static.toiimg.com',
        'static0.anpoimages.com',
        'static.clubs.nfl.com',
        'static.dw.com',
        'twt-thumbs.washtimes.com',
        'variety.com',
        'www.aljazeera.com',
        'www.bgr.com',
        'www.challenges.fr',
        'www.dhnet.be',
        'www.franceinfo.fr',
        'www.hollywoodreporter.com',
        'www.journaldugeek.com',
        'www.lalibre.be',
        'www.lavenir.net',
        'www.lefigaro.fr',
        'www.lejournaldesentreprises.com',
        'www.lexpress.fr',
        'www.opinion-internationale.com',
        'www.phoronix.net',
        'www.sciencealert.com',
        'www.sciencedaily.com',
        'www.telegraph.co.uk',
        'www.thestreet.com',
        'www.usatoday.com',
        'www.valeursactuelles.com',
        'www.washingtonpost.com',
    ],

    'article_hero_cache_seconds' => 60 * 60 * 24 * 30,
    'logo_cache_seconds' => 60 * 60 * 24 * 7,
    'max_bytes' => 8 * 1024 * 1024,
];
